apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: kc-admin-allow
  namespace: keycloak
spec:
  ingressClassName: apisix
  http:
  - name: allow-admin-api
    priority: 1
    match:
      hosts:
      - kc-admin.local
      paths:
      - /admin/realms/master/users
    backends:
    - serviceName: kc-keycloak
      servicePort: 80

